Repository Q-CARD/QCard-server, pull requests merged in 2023-09, with the labels that each got.

#23 [FIX] 답변 수정 api의 request dto 변경
  q-api/src/main/java/com/qcard/api/answer/controller/AnswerController.java
  q-api/src/main/java/com/qcard/api/answer/service/AnswerService.java
  scripts/stop.sh
Labels: bug

#25 [HOTFIX] CORS 에러 해결
  q-admin/src/main/java/com/qcard/config/WebConfig.java
Labels: bug

#24 [FIX] 비번 검사 및 계정 중복 검사 추가
  q-admin/src/main/java/com/qcard/jwt/JwtService.java
  q-api/build.gradle
  q-api/src/main/java/com/qcard/api/account/controller/AccountController.java
  q-api/src/main/java/com/qcard/api/account/dto/AccountReq.java
  q-api/src/main/java/com/qcard/api/account/dto/SignInReq.java
  q-api/src/main/java/com/qcard/api/account/service/AccountService.java
  q-domain/src/main/java/com/qcard/domains/account/entity/Account.java
  q-domain/src/main/java/com/qcard/domains/account/repository/AccountRepository.java
  q-domain/src/main/java/com/qcard/domains/account/service/AccountDomainService.java
Labels: bug

#26 [FIX] 비번 검사 및 계정 중복 검사 추가
  q-admin/src/main/java/com/qcard/jwt/JwtService.java
  q-api/build.gradle
  q-api/src/main/java/com/qcard/api/account/controller/AccountController.java
  q-api/src/main/java/com/qcard/api/account/dto/AccountReq.java
  q-api/src/main/java/com/qcard/api/account/dto/SignInReq.java
  q-api/src/main/java/com/qcard/api/account/service/AccountService.java
  q-domain/src/main/java/com/qcard/domains/account/entity/Account.java
  q-domain/src/main/java/com/qcard/domains/account/repository/AccountRepository.java
  q-domain/src/main/java/com/qcard/domains/account/service/AccountDomainService.java
Labels: bug

#27 [FIX] 답변리스트 없어도 질문상세정보 조회가능
  q-api/src/main/java/com/qcard/api/answer/service/AnswerService.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionDetailRes.java
Labels: bug

#30 [FEAT] 메인화면 랜덤질문 & 질문모음집 반환 api
  q-api/src/main/java/com/qcard/api/question/dto/QuestionMainRes.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionZipRes.java
  q-api/src/main/java/com/qcard/api/question/service/QuestionService.java
  q-common/src/main/java/com/qcard/common/enums/Category.java
  q-domain/src/main/java/com/qcard/domains/question/service/QuestionDomainService.java
Labels: new feature

#31 [FEAT] /question Detail Dto 반환 시 gpt 응답 추가
  q-api/src/main/java/com/qcard/api/answer/dto/AnswerRes.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionDetailRes.java
  q-domain/src/main/java/com/qcard/domains/question/repository/AnswerRepository.java
  q-domain/src/main/java/com/qcard/domains/question/service/AnswerDomainService.java
Labels: enhancement

#34 [FEAT]토큰 재발급 및 로그아웃 구현
  docker-compose.yaml
  gradlew
  q-admin/build.gradle
  q-admin/src/main/java/com/qcard/config/WebConfig.java
  q-admin/src/main/java/com/qcard/jwt/JwtFilter.java
  q-admin/src/main/java/com/qcard/jwt/JwtService.java
  q-admin/src/main/java/com/qcard/jwt/JwtUtil.java
  q-admin/src/main/java/com/qcard/redis/RedisConfig.java
  q-admin/src/main/java/com/qcard/redis/RedisService.java
  q-admin/src/main/java/com/qcard/resolver/AuthAccount.java
  q-admin/src/main/java/com/qcard/resolver/AuthAccountArgumentResolver.java
  q-admin/src/main/java/com/qcard/service/CustomUserDetailService.java
  q-api/src/main/java/com/qcard/api/account/controller/AccountController.java
  q-api/src/main/java/com/qcard/api/account/dto/LogOutRes.java
  q-api/src/main/java/com/qcard/api/account/service/AccountService.java
  q-api/src/main/java/com/qcard/api/answer/controller/AnswerController.java
  q-api/src/main/java/com/qcard/api/answer/dto/AnswerMeRes.java
  q-api/src/main/java/com/qcard/api/heart/controller/HeartController.java
  q-api/src/main/java/com/qcard/api/question/controller/QuestionController.java
  q-domain/src/main/java/com/qcard/domains/account/entity/Account.java
  scripts/run-local.sh
  scripts/stop-local.sh
Labels: new feature

#36 [CHORE] 배포 스크립트 변경
  .github/workflows/gradle.yml
  scripts/deploy.sh
  scripts/stop.sh
Labels: enhancement

#42 [FEAT]질문모음집 api 파라미터 및 페이지네이션 기능
  build.gradle
  q-admin/src/main/java/com/qcard/resolver/AuthAccountArgumentResolver.java
  q-api/src/main/java/com/qcard/api/answer/controller/AnswerController.java
  q-api/src/main/java/com/qcard/api/answer/dto/AnswerMeRes.java
  q-api/src/main/java/com/qcard/api/answer/dto/AnswerRes.java
  q-api/src/main/java/com/qcard/api/answer/service/AnswerService.java
  q-api/src/main/java/com/qcard/api/question/controller/QuestionController.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionDetailRes.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionMainRes.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionParam.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionReq.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionRes.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionSimpleRes.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionZipRes.java
  q-api/src/main/java/com/qcard/api/question/service/QuestionService.java
  q-common/src/main/java/com/qcard/common/dto/QuestionFilterReq.java
  q-common/src/main/java/com/qcard/common/enums/AnswerType.java
  q-common/src/main/java/com/qcard/common/enums/Category.java
  q-common/src/main/java/com/qcard/common/enums/QuestionType.java
  q-common/src/main/java/com/qcard/common/enums/SortType.java
  q-domain/build.gradle
  q-domain/src/main/generated/com/qcard/domains/account/entity/QAccount.java
  q-domain/src/main/generated/com/qcard/domains/heart/entity/QHeart.java
  q-domain/src/main/generated/com/qcard/domains/interview/entity/QInterview.java
  q-domain/src/main/generated/com/qcard/domains/question/entity/QAnswer.java
  q-domain/src/main/generated/com/qcard/domains/question/entity/QQuestion.java
  q-domain/src/main/java/com/qcard/config/QueryDslConfig.java
  q-domain/src/main/java/com/qcard/domains/question/entity/Answer.java
  q-domain/src/main/java/com/qcard/domains/question/entity/Question.java
  q-domain/src/main/java/com/qcard/domains/question/repository/AnswerRepository.java
  q-domain/src/main/java/com/qcard/domains/question/repository/AnswerRepositoryCustom.java
  q-domain/src/main/java/com/qcard/domains/question/repository/QuestionRepository.java
  q-domain/src/main/java/com/qcard/domains/question/repository/QuestionRepositoryCustom.java
  q-domain/src/main/java/com/qcard/domains/question/service/AnswerDomainService.java
  q-domain/src/main/java/com/qcard/domains/question/service/AnswerRepositoryImpl.java
  q-domain/src/main/java/com/qcard/domains/question/service/QuestionDomainService.java
  q-domain/src/main/java/com/qcard/domains/question/service/QuestionRepositoryImpl.java
  scripts/stop-local.sh
Labels: enhancement

#44 [FEAT] 프로필 반환, 프로필 변경 기능 추가
  q-api/src/main/java/com/qcard/api/account/controller/AccountController.java
  q-api/src/main/java/com/qcard/api/account/dto/AccountModifyReq.java
  q-api/src/main/java/com/qcard/api/account/dto/AccountRes.java
  q-api/src/main/java/com/qcard/api/account/service/AccountService.java
  q-api/src/main/java/com/qcard/api/answer/controller/AnswerController.java
  q-api/src/main/java/com/qcard/api/answer/dto/AnswerMeRes.java
  q-api/src/main/java/com/qcard/api/answer/dto/AnswerRes.java
  q-api/src/main/java/com/qcard/api/answer/service/AnswerService.java
  q-api/src/main/java/com/qcard/api/question/dto/QuestionRes.java
  q-domain/src/main/generated/com/qcard/domains/account/entity/QAccount.java
  q-domain/src/main/java/com/qcard/domains/account/entity/Account.java
  q-domain/src/main/java/com/qcard/domains/account/service/AccountDomainService.java
  q-domain/src/main/java/com/qcard/domains/question/repository/AnswerRepository.java
  q-domain/src/main/java/com/qcard/domains/question/service/AnswerDomainService.java
Labels: enhancement
